export const actions = {
    TOGGLE_INTEGRATION: 'TOGGLE_INTEGRATION',
    INTEGRATION_CREATED: 'INTEGRATION_CREATED',
    INTEGRATION_READY: 'INTEGRATION_READY',
    INTEGRATION_CLOSED: 'INTEGRATION_CLOSED',
    CREATE_WINDOW: 'CREATE_WINDOW',
    REMOVE_WINDOW: 'REMOVE_WINDOW',
    NEW_INTEGRATION: 'NEW_INTEGRATION',
    SHOW_WINDOW: 'SHOW_WINDOW',
    WINDOW_LOADED: 'WINDOW_LOADED',
    WINDOW_CLOSING: 'WINDOW_CLOSING',
    WINDOW_CLOSED: 'WINDOW_CLOSED',
    WINDOW_EVENT: 'WINDOW_EVENT',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    TOKEN_REFRESHED: 'TOKEN_REFRESHED',
    SUBSCRIBE_TOKEN_REFRESH: 'SUBSCRIBE_TOKE_REFRESH',
    UNSUBSCRIBE_TOKEN_REFRESH: 'UNSUBSCRIBE_TOKEN_REFRESH',
    LOAD_WINDOW: 'LOAD_WINDOW'
};